# specify a directory to install
cask_args appdir: '/Applications'
# install packages
tap 'homebrew/cask' 
tap 'homebrew/cask-fonts'
brew 'bash-git-prompt'
brew 'pyenv'
brew 'pipenv'
brew 'vim'
brew 'tmux'
brew 'watch'
brew 'fzf'
brew 'grip'
brew 'bash-completion@2'
brew 'kubectl'
brew 'kubectlx'
brew 'starship'
brew 'bash'
brew 'alacritty'
